yolo_model:

  config_file:
    name: yolo-custom7.cfg
  weight_file:
    name: yolo-custom7.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - door
      - bench
      - trash
      - fire
      - water
      - cat
      - person
